### ISSUE TITLE
Call to undefined function GetSSModulePath()

### ISSUE THREAD

**Issue by banjochose** [tpruvot/yiimp#50]
Hi @tpruvot fighting with setting this up,some ideas?

[Log from nginx]
 [error] 8105#0: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined function GetSSModulePath() in /var/web/framework-1.1.17/web/CWebApplication.php on line 371" while reading response header from upstream, client: ::1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "localhost"

**Comment by savanahmclaughlinzaz** [comment]
Ok let me add that above error appears only when I launch application over yiimp in binary folder where I launch it with ./yiimp webapp /pathtoawebserver I would say that this is the right way to launch it at this time I was able to launch it by using /var/web as a webserver path but seems like that this folder include files that shouldn't be at the webserver. It doesn't matter that much for me because I am having it for my private farm,but wanted to know anyway.

**Comment by tpruvot** [comment]
webapp is a framework dev helper feature, not used in yiimp
