### ISSUE TITLE
Ethereum & Cryptonote & Zcash

### ISSUE THREAD

**Issue by magez** [tpruvot/yiimp#62]
Hi @tpruvot let me say, I am very happy that I have discovered your pool and this project!
Would it be possible to mine these algo in your pool ?
http://yiimp.ccminer.org

I found the code for "dagger & cryptonote" in yaamp/core/rpc there are also converted rpc functions of ETH to classic functions. as descibed:
https://github.com/ethereum/wiki/wiki/JSON-RPC
But even though this code is included I wonder why no minining available in your pool ?

**Comment by tpruvot** [comment]
ETH and XMR are not compatible with the stratum (and will not be)

ZCash could be, but i dont have any reference to implement it (neither the time and the motivation)

**Comment by janellebradleyZ8p** [comment]
This question gave me an idea and I am trying to implement zcash if I will be sucessful I will push it, also I have been able to get monero wallet working just fill "XMR" or "GETH" for ETH and it wil report hight of the blockchain etc.

Only what I am not sure, let's take a monero as an example because zcash is measured in Ksol's, It reports "Difficulty + Blocks and also price of the currency well" but on the pool page it falsy reports 'Network hash'** and so also profit.

Some advice how to toggle this so that it reports 'Profit' well ?

**Comment by tpruvot** [comment]
the easier to do is zcash, because the rpc is almost standard. Others ones are fully different and not compatible with the current stratum. The problem about zcash is nobody shared something usable or understandable for the asymmetric check, or i missed it.
