### ISSUE TITLE
blocknotify-dcr

### ISSUE THREAD

**Issue by janellebradleyZ8p** [tpruvot/yiimp#66]
After some rough time with setting up decred I finally run it in yaamp!

These were required to run:
dcrd --notls
dcrwallet --rpclisten=127.0.0.1:9113 --noclienttls --noservertls

But the main issue I do not know how to get around is compiling blocknotify for the decred.

./blocknotify.go:50: bhead.BlockSha undefined (type wire.BlockHeader has no field or method BlockSha)

**Comment by tpruvot** [comment]
https://github.com/tpruvot/yiimp/pull/65

**Comment by cryptoman2** [comment]
Dear janellebradleyZ8p,
can you please help me with DCR setup? I tried many different configurations but not reched result.
Shortly what I have done:
Compiling startum, blocknotify and blocknotify-dcr was OK, site also forks fine, but I can't understand how to maki stratum to work.
First i start dcrd wish followong command:
dcrd --notls -u user -P pass --miningaddr=DsfSBW4h3Uu1ftpyJWRGfbtF8XxAVL9aXFV
After start wallet with following command:
dcrwallet --rpclisten=127.0.0.1:9113 --noclienttls --noservertls -u user -P pass
All fine, wallet is connected to dcrd and ready to work.
Then I start blocknotify-dcr , he also start work correctly (in output I see "NotifyBlocks: Registration Complete"
Then I tried to start stratum, but it can't get work from coin:
22:40:04: 2017-04-20 starting stratum for decred on dcr.mypool.com:5744
22:40:04: connecting to coind DCR
22:40:27: DCR getwork retry 1
22:40:27: DCR getwork retry 2
22:40:28: DCR error getwork

In DB, in table coins I specify rpcport 9113, it mean stratum tried to connect to wallet, not to dcrd, is it correct? If I specify port 9109 - stratum not started also. Please help, because it make me crazy :)

**Comment by tpruvot** [comment]
the stratum connects only to the wallet (which receive and distribute the mined blocks)

the notify tool is optional, it only confirm faster the found blocks to keep the finder address

**Comment by tpruvot** [comment]
try to type getwork in the web console, i guess it returns an error
